name: Java CI

on: [push]

jobs:
  build-ubuntu-mac:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]

    steps:
      - uses: actions/checkout@v1
      - uses: DeLaGuardo/setup-graalvm@4.0
        with:
          # GraalVM version, no pattern syntax available atm
          graalvm: '21.0.0.2'
          # Java version, optional, defaults to 'java8'. Available options are 'java8' and 'java11'.
          java: 'java11'
          # Architecture flag, optional, defaults to 'amd64'. Available options are 'amd64' and 'aarch64'. Later is available only for linux runners.
          arch: 'amd64'
      - run: java -version
      - run: gu install native-image
      - name: Build with Gradle
        run: ./gradlew nativeImage
      - name: ls build
        shell: bash
        run: ls -lRt build
      - name: Rename the artifact to OS-unique name
        shell: bash
        run: |
          value=`cp build/native-image/perfiz build/native-image/perfiz-${{ matrix.os }}`
      - name: Publish artifact
        uses: actions/upload-artifact@master
        with:
          name: perfiz-${{ matrix.os }}
          path: build/native-image
